# Generated by Django 5.0.4 on 2024-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(max_length=10)),
                ('ename', models.CharField(max_length=20)),
                ('eemail', models.EmailField(max_length=20)),
                ('econtact', models.IntegerField(max_length=10)),
                ('edept', models.TextField(max_length=15)),
                ('ecity', models.TextField(max_length=20)),
            ],
        ),
    ]
