# Generated by Django 5.0.4 on 2024-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ecity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='edept',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254),
        ),
    ]
